trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-pipelines.yaml
    exclude:
    - Readme.md

resources:
- repo: self

variables:
  IMAGE_NAME: gokul2609/album-backend-api
  CONTAINERAPPS_APP: myimage01
  CONTAINERAPPS_ENVIRONMENT: managedEnvironment-aca-851b
  RESOURCE_GROUP: aca
  TAG: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/az400-container-apps/Dockerfile'
        repository: $(IMAGE_NAME)
        tags: $(TAG)

    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: 'dockerhub'
        repository: $(IMAGE_NAME)
        command: 'push'
        tags: '$(TAG)'

- stage: Deploy
  displayName: Deploy to Container Apps
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AzureContainerApps@1
      displayName: Deploy new container version
      inputs:
        azureSubscription: 'mypipelines'
        imageToDeploy: '$(IMAGE_NAME):$(TAG)'
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '3500'
        ingress: 'external'
